package edu.jimei.praesidium.dto;

import lombok.Builder;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * DTO for the response of a query.
 *
 * @author Advisor
 */
@Data
@Builder
public class QueryResponse implements Serializable {

    /**
     * The suggested answer generated by the AI.
     */
    private String suggestedAnswer;

    /**
     * The confidence score of the suggested answer, ranging from 0.0 to 1.0.
     */
    private double confidence;

    /**
     * A list of keywords identified from the user's query.
     */
    private List<String> keywordAnalysis;

    /**
     * A flag indicating whether the query could not be confidently answered and requires human review.
     */
    private boolean needsHumanReview;

} 