CREATE TABLE service_qa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    answer TEXT NOT NULL
);

CREATE TABLE service_qa_keywords (
    service_qa_id BIGINT NOT NULL,
    keyword VARCHAR(255),
    CONSTRAINT fk_service_qa_keywords_service_qa FOREIGN KEY (service_qa_id) REFERENCES service_qa(id)
); 